// Package aubank parses AU Small Finance Bank account statement PDFs.
//
// AU Bank PDFs use an RTL-encoded font where every character is a separate
// text element with X positions running right-to-left within each word.
// We use GroupByRowsNaturalOrder + ReconstructText to restore reading order.
//
// Each transaction is spread across several visual rows:
//
//	pre-row  : "UPI/DR/570161013279/BA  ICIa65a07aa510943"   (desc start + ref start)
//	main row : "01Dec2025 01Dec2025 NGALOREHARTICULTURE b98… 45.00 - 1,25,912.58"
//	cont rows: "FRUITSAND c", "VEGETABLES/YESB/…", "JAGATPURA"
//
// The main row always contains at least one date and two amounts.
// Pre-rows + description portion of main row + continuation rows form the
// full description.
package aubank

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/Yashswarnkar/expense-classifier/internal/models"
	pdfread "github.com/Yashswarnkar/expense-classifier/internal/pdf"
)

const (
	rowTol = 4.0
	// colGapFactor: an X jump larger than colGapFactor × charWidth is treated
	// as a column separator rather than a word gap. AU Bank column gaps are
	// typically 20–40× the character width, while word gaps are 1–3×.
	// RTL-encoded fonts can have word-boundary X jumps up to ~9× charWidth,
	// so we use 20 to avoid false splits within the description column.
	colGapFactor = 20.0
)

var (
	// Handles both "01Dec2025" (no spaces, from ReconstructText) and "01 Dec 2025"
	dateRe = regexp.MustCompile(`\b(\d{2}\s*[A-Za-z]{3}\s*\d{4})\b`)

	// Indian-format amounts: "45.00", "1,25,912.58"
	amountRe = regexp.MustCompile(`\b([\d,]+\.\d{2})\b`)

	// Captures the three trailing cells: debit|"-"  credit|"-"  balance
	// Examples:
	//   "45.00 - 1,25,912.58"   → debit=45.00  credit=-       balance=1,25,912.58
	//   "- 2.00 53,717.56"      → debit=-       credit=2.00    balance=53,717.56
	amountTripletRe = regexp.MustCompile(`([\d,]+\.\d{2}|-)\s+([\d,]+\.\d{2}|-)\s+([\d,]+\.\d{2})\s*$`)

	// refSuffixRe strips a trailing bank transaction reference that leaks into
	// the description from the main row (e.g. "YESb98abc1234567890").
	// Pattern: 0–4 uppercase letters followed by 8+ lowercase hex chars.
	refSuffixRe = regexp.MustCompile(`\s+[A-Z]{0,4}[a-f0-9]{8,}\s*$`)

	stopWords = []string{
		"account statement", "statement date", "opening balance",
		"closing balance", "this is an auto", "call us at",
		"transaction date", "value date", "description/narration",
		"cheque/reference", "debit", "credit", "balance",
	}

	// footerRe matches page-footer rows that must never become part of a description.
	// Examples:
	//   "Page23 of23", "Page 2 of 10"
	//   "Total 5,19,162.18 5,35,153.29"
	//   "Thisisanautogeneratedstatement" (compacted, no spaces)
	//   "www.aubank.in", "customercare@aubank.in"
	footerRe = regexp.MustCompile(
		`(?i)` +
			`page\s*\d+\s*of\s*\d+` +
			`|^total\s+([\d,]+\.\d{2}\s*){2,}` +
			`|thisisanauto` +
			`|aubank\.in` +
			`|customercare` +
			`|autogenerated`,
	)
)

// Parser implements parser.Parser for AU Bank account statements.
type Parser struct{}

func New() *Parser { return &Parser{} }

func (p *Parser) Name() string              { return "AU Bank Account Statement" }
func (p *Parser) Source() models.SourceType { return models.SourceAUBank }

func (p *Parser) Parse(filePath, password string) ([]*models.Transaction, error) {
	pages, err := pdfread.DecryptAndExtract(filePath, password)
	if err != nil {
		return nil, fmt.Errorf("aubank: extract text: %w", err)
	}

	var txns []*models.Transaction
	for _, page := range pages {
		rows := pdfread.GroupByRowsNaturalOrder(page.Elements, rowTol)
		txns = append(txns, parsePageRows(rows)...)
	}
	return txns, nil
}

// parsePageRows is the core parser.
//
// Pass 1: reconstruct text for every row.
// Pass 2: identify "main rows" — rows that contain ≥1 date AND ≥2 amounts.
// Pass 3: for each main row at index m, the transaction block spans rows
//
//	[prev_main+1 … next_main-2]
//
// The -2 is because (next_main-1) is always the pre-row of the next
// transaction (containing the start of the next description), which belongs
// to the next transaction, not the current one.
func parsePageRows(rows [][]pdfread.TextElement) []*models.Transaction {
	texts := make([]string, len(rows))
	for i, row := range rows {
		texts[i] = pdfread.ReconstructText(row)
	}

	// Find main row indices: rows that contain a date AND the amount triplet.
	var mainIdxs []int
	for i, t := range texts {
		if len(findDates(t)) > 0 && amountTripletRe.MatchString(t) {
			mainIdxs = append(mainIdxs, i)
		}
	}

	var txns []*models.Transaction

	for i, mainIdx := range mainIdxs {
		// Block start: row after previous main row (or 0).
		blockStart := 0
		if i > 0 {
			blockStart = mainIdxs[i-1] + 1
		}

		// Block end: two rows before next main row (or end of page).
		// next_main-1 is the pre-row of the next transaction.
		blockEnd := len(texts) - 1
		if i+1 < len(mainIdxs) {
			blockEnd = mainIdxs[i+1] - 2
			if blockEnd < mainIdx {
				blockEnd = mainIdx
			}
		}

		// Gather description text from every row in the block.
		// Non-main rows are split at the first column gap so that the
		// Cheque/Reference column does not leak into the description.
		var descParts []string
		var refNo string
		for j := blockStart; j <= blockEnd; j++ {
			t := strings.TrimSpace(texts[j])
			if t == "" || isNonTxnRow(t) {
				continue
			}
			if j == mainIdx {
				// Strip dates, amounts, and balance from the main row —
				// what remains is the middle portion of the description.
				// Also strip any trailing bank reference suffix.
				t = descFromMainRow(t)
				t = refSuffixRe.ReplaceAllString(t, "")
				t = cleanDesc(t)
			} else {
				// For pre-rows and continuation rows, split at the first
				// large X gap (column boundary) to separate description
				// from the Cheque/Reference column.
				desc, ref := firstAndSecondColumn(rows[j])
				t = desc
				if refNo == "" && ref != "" {
					refNo = ref
				}
			}
			if t != "" {
				descParts = append(descParts, t)
			}
		}

		desc := cleanDesc(strings.Join(descParts, " "))
		dates := findDates(texts[mainIdx])

		txn := buildTxn(dates, texts[mainIdx], desc, refNo)
		if txn != nil {
			txn.Hash = txn.ComputeHash()
			txns = append(txns, txn)
		}
	}

	return txns
}

// buildTxn assembles a Transaction from the parsed dates, raw main-row text,
// and collected description.
//
// It uses amountTripletRe to match the three trailing cells of the main row:
//
//	debit_cell  credit_cell  balance
//
// where each of debit_cell / credit_cell is either a number or "-".
// This is the only reliable way to distinguish debit from credit because
// the "-" placeholder is lost when scanning for numeric amounts alone.
func buildTxn(dates []time.Time, mainRowText, desc, refNo string) *models.Transaction {
	if len(dates) == 0 || desc == "" {
		return nil
	}

	m := amountTripletRe.FindStringSubmatch(mainRowText)
	if m == nil {
		return nil // no amount triplet found — not a transaction row
	}

	debitStr, creditStr, balanceStr := m[1], m[2], m[3]

	debit, _ := parseIndianAmt(debitStr)   // 0 when debitStr == "-"
	credit, _ := parseIndianAmt(creditStr) // 0 when creditStr == "-"
	balance, _ := parseIndianAmt(balanceStr)

	var amount float64
	txnType := models.TxnDebit

	switch {
	case debit > 0 && credit == 0:
		amount = debit
		txnType = models.TxnDebit
	case credit > 0 && debit == 0:
		amount = credit
		txnType = models.TxnCredit
	default:
		return nil // both zero or both non-zero — skip
	}

	txnDate := dates[0]
	var valueDate *time.Time
	if len(dates) >= 2 {
		d := dates[1]
		valueDate = &d
	}

	return &models.Transaction{
		ID:              uuid.New().String(),
		Source:          models.SourceAUBank,
		TransactionDate: txnDate,
		ValueDate:       valueDate,
		Description:     desc,
		ReferenceNo:     refNo,
		Amount:          amount,
		Type:            txnType,
		Balance:         balance,
		Category:        "Uncategorized",
		CreatedAt:       time.Now(),
	}
}

// descFromMainRow strips dates and the amount triplet from a main row,
// leaving just the description/reference fragment in the middle.
func descFromMainRow(text string) string {
	text = dateRe.ReplaceAllString(text, " ")
	text = amountTripletRe.ReplaceAllString(text, " ")
	// Also remove any leftover standalone amounts or dashes.
	text = amountRe.ReplaceAllString(text, " ")
	text = regexp.MustCompile(`\s+-\s*$`).ReplaceAllString(text, " ")
	return cleanDesc(text)
}

// findDates extracts and parses all date tokens from text.
// Handles both "01Dec2025" and "01 Dec 2025".
func findDates(text string) []time.Time {
	matches := dateRe.FindAllString(text, -1)
	var dates []time.Time
	seen := map[string]bool{}
	for _, m := range matches {
		m = strings.Join(strings.Fields(m), "") // "01 Dec 2025" → "01Dec2025"
		if seen[m] {
			continue
		}
		seen[m] = true
		// Try compact layout first, then spaced.
		t, err := time.Parse("02Jan2006", m)
		if err != nil {
			spaced := m[:2] + " " + m[2:5] + " " + m[5:]
			t, err = time.Parse("02 Jan 2006", spaced)
		}
		if err == nil {
			dates = append(dates, t)
		}
	}
	return dates
}

func parseIndianAmt(s string) (float64, error) {
	s = strings.TrimSpace(s)
	if s == "-" || s == "" {
		return 0, nil
	}
	s = strings.ReplaceAll(s, ",", "")
	return strconv.ParseFloat(s, 64)
}

func isNonTxnRow(text string) bool {
	lower := strings.ToLower(text)
	for _, w := range stopWords {
		if strings.Contains(lower, w) {
			return true
		}
	}
	return footerRe.MatchString(text)
}

func cleanDesc(s string) string {
	return strings.TrimSpace(strings.Join(strings.Fields(s), " "))
}

// firstAndSecondColumn splits a row's elements at the first large X gap
// (column boundary) and returns the text of the first column (description)
// and second column (reference / other). If no column boundary is detected,
// the whole row is returned as the first column and ref is empty.
func firstAndSecondColumn(row []pdfread.TextElement) (desc, ref string) {
	if len(row) == 0 {
		return "", ""
	}

	var col strings.Builder
	col.WriteString(row[0].Content)
	splitAt := -1

	for i := 1; i < len(row); i++ {
		prev := row[i-1]
		curr := row[i]

		charW := prev.FontSize * 0.55
		if charW < 3 {
			charW = 5
		}
		xDiff := curr.X - prev.X

		if splitAt < 0 && xDiff > charW*colGapFactor {
			// First column boundary — save col1, start col2.
			desc = cleanDesc(col.String())
			col.Reset()
			col.WriteString(curr.Content)
			splitAt = i
			continue
		}

		// Within whichever column we're in, apply the same spacing logic
		// as ReconstructText.
		if xDiff > charW {
			col.WriteByte(' ')
		} else if xDiff < -(charW * 2.8) {
			col.WriteByte(' ')
		}
		col.WriteString(curr.Content)
	}

	if splitAt < 0 {
		return cleanDesc(col.String()), ""
	}
	return desc, cleanDesc(col.String())
}
